---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/movies":
    get:
      summary: list movies
      tags:
      - Movies
      description: "Following endpoint accepts three types of query parameters:\n\n
        \     include accepts 'actors', 'directors' or both 'actors,directors'. Adding
        include parameter provides to render movie's data with director/actors names'.\n\n
        \     sort accepts '-year', 'year', '-budget', 'budget', '-imdb_score', 'imdb_score'.
        This parameter has impact on sorting rendered movies. '-year' parameter provides
        to sort movies by release_year in descending order wheras 'year' the other
        way around. By analogy '-budget', 'budget' and '-imdb_score', 'imdb_score'\n\n
        \     filter[actor_id] accepts actors ids. This parameter causes rendering
        only movies which filtered actor was acting in. \n\n      filter[director_id]
        accepts directors ids. This parameter causes rendering only movies directed
        by filtered director."
      parameters:
      - name: include
        in: query
        schema:
          type: string
      - name: sort
        in: query
        schema:
          type: string
      - name: filter[actor_id]
        in: query
        schema:
          type: string
      - name: filter[director_id]
        in: query
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                raw_movie_data:
                  value:
                    name: The Hateful Eight
                    release_year: '2015'
                    budget: '44000000'
                    imdb_score: '7.8'
                with_included_director_data:
                  value:
                    name: The Hateful Eight
                    release_year: '2015'
                    budget: '44000000'
                    imdb_score: '7.8'
                    director:
                      name: Quentin Tarantino
                with_included_actors_data:
                  value:
                    name: The Hateful Eight
                    release_year: '2015'
                    budget: '44000000'
                    imdb_score: '7.8'
                    actors:
                    - name: Samuel L. Jackson
                    - name: Kurt Russell
                with_included_director_and_actors_data:
                  value:
                    name: The Hateful Eight
                    release_year: '2015'
                    budget: '44000000'
                    imdb_score: '7.8'
                    director:
                      name: Quentin Tarantino
                    actors:
                    - name: Samuel L. Jackson
                    - name: Kurt Russell
              schema:
                type: array
                properties:
                  name:
                    type: string
                  release_year:
                    type: string
                  budget:
                    type: string
                  imdb_score:
                    type: string
                  actors:
                  - name:
                      type: string
                  director:
                    name:
                      type: string
    post:
      summary: create movie
      tags:
      - Movies
      description: |-
        Creating a new movie causes:

              - saving movie, director, actors and genres to database,

              - sending e-mail with information about new movie to newsletter members,

              -- updating director's data(movies_count, total_budget_of_movies),

              -- rendering json with new movie data including director and actors informations.

              If any of following parameters do not meet the requirements, we will reach 422 response with rendered errors in json format.
      parameters:
      - name: movie
        in: query
        schema:
          type: object
          properties:
            movie[name]:
              type: string
            movie[release_year]:
              type: string
            movie[budget]:
              type: string
            movie[imdb_score]:
              type: string
            movie[director_name]:
              type: string
            movie[actors_names]:
              type: string
            movie[genres_names]:
              type: string
      responses:
        '200':
          description: movie created
          content:
            application/json:
              examples:
                successful_creation_of_new_movie:
                  value:
                    movie:
                      name: The Hateful Eight
                      release_year: '2015'
                      budget: '44000000'
                      imdb_score: '7.8'
                      actors:
                      - name: Samuel L. Jackson
                      - name: Kurt Russell
                      director:
                        name: Quentin Tarantino
        '422':
          description: unprocessable_entity
          content:
            application/json:
              examples:
                failure_to_create_new_movie:
                  value:
                    name:
                    - can't be blank, Movie with this name already exists
                    release_year:
                    - Release year is not a number
                    budget:
                    - Budget is not a number
                    imdb_score:
                    - IMDb score is not a number
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
